sudo: required
install:
- sudo apt-get install --yes doxygen graphviz
env:
global:
secure: C3Nakbhm9XZMKXjlTVsoU61Gvk1vtinkat7B57izLEtRDM5uXXHnn7KoVS3D3Jw+gyylJHD8OiYkIOacbmPMqWDUvUfSffLS23IXv9+cG6QApci0eRgnQTp6680pyK8ffPk2YAhrJmpeW7RStNEXiiUfkBYMspQd6o7yQZ3gmQA= 
language: csharp
solution: better-bots/Britbot/Britbot.sln
after_success: 
- ./doxybuild.sh